services:
  validate:
    image: validate
    restart: always
    env_file:
      - .env
    ports:
      - 3001:3001
    networks:
      docker_net:
        ipv4_address: 192.168.25.11
  graphana:
    image: grafana/grafana:latest
    restart: always
    env_file:
      - .env
    ports:
      - "3000:3000"
    volumes:
      - ./grafana-provisioning/:/etc/grafana/provisioning/
      - ./grafana-db/:/var/lib/grafana/
    networks:
      docker_net:
        ipv4_address: 192.168.25.12
  prometheus:
    image: prom/prometheus:latest
    restart: always
    volumes:
      - ./prometheus/config:/etc/prometheus
      - ./prometheus/data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    ports:
      - "9090:9090"
    networks:
      docker_net:
        ipv4_address: 192.168.25.14
  nginx:
    image: nginx:latest
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx-selfsigned.crt:/etc/ssl/certs/nginx-selfsigned.crt:ro
      - ./nginx-selfsigned.key:/etc/ssl/private/nginx-selfsigned.key:ro
    depends_on:
      - validate
    networks:
      docker_net:
        ipv4_address: 192.168.25.13
  
networks:
  docker_net:
    external: true
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.25.0/24
